import os
import json
import datetime
from groq import Groq
from dotenv import load_dotenv

# Load API Key
load_dotenv()
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

# Inisialisasi Client Groq
client = Groq(api_key=GROQ_API_KEY) 

def generate_summary(news_data):
    """
    Menerima list berita, mengirim ke AI, dan mengembalikan teks HTML siap kirim.
    """
    # Cek jika data kosong
    if not news_data:
        return None

    print("🧠 AI sedang meracik laporan estetik...")

    today = datetime.date.today().strftime("%d %B %Y")

    # Susun data berita menjadi teks string agar bisa dibaca AI
    news_text = ""
    for i, item in enumerate(news_data, 1):
        # Kita handle jika snippet tidak ada
        snippet = item.get('snippet', 'Tidak ada ringkasan.')
        news_text += f"Berita {i}:\nJudul: {item['title']}\nLink: {item['link']}\nRingkasan: {snippet}\n\n"

    # --- SYSTEM PROMPT (Instruksi Otak AI) ---
    system_prompt = f"""
    Kamu adalah asisten riset pribadi bernama 'Ruphas AI'.
    Tugasmu adalah membuat newsletter teknologi harian yang rapi dan profesional untuk pemilikmu (Ruphas).
    
    ATURAN FORMATTING (PENTING):
    1. Output HARUS dalam format HTML sederhana yang didukung Telegram.
    2. GUNAKAN tag `<b>` untuk menebalkan teks.
    3. GUNAKAN tag `<i>` untuk memiringkan teks.
    4. GUNAKAN tag `<a href="URL">Teks Link</a>` untuk link.
    5. JANGAN gunakan format Markdown (seperti **bold** atau [link](url)), karena akan menyebabkan error.

    STRUKTUR LAPORAN:
    
    1. HEADER:
       Tulis "📰 <b>DAILY TECH UPDATE</b>"
       Tulis tanggal hari ini: {today}
    
    2. OPENING:
       Sapa Ruphas dengan singkat, ramah, dan energik.

    3. ISI BERITA (Pilih 3-5 berita paling relevan):
       Untuk setiap berita, gunakan format ini:
       
       🔹 <b>Judul Berita</b>
       📝 <i>Summary:</i> Rangkuman intisari dalam 1 kalimat padat.
       🎯 <i>Impact:</i> Satu kalimat singkat kenapa berita ini penting bagi developer/tech enthusiast.
       🔗 <a href="LINK_ASLI_BERITA">Baca Selengkapnya</a>
       
       (Berikan jarak satu baris kosong antar berita)

    4. CLOSING:
       Satu kalimat motivasi pendek untuk Programmer/Developer agar semangat coding.
       Akhiri dengan footer: "🚀 <i>Generated by Ruphas AI Assistant</i>"
    """

    # --- KIRIM KE GROQ ---
    try:
        chat_completion = client.chat.completions.create(
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"Ini data beritanya:\n{news_text}"}
            ],
            model="llama-3.3-70b-versatile", 
            temperature=0.6, # 0.6 agar seimbang antara kreatif dan faktual
        )

        # Ambil hasil
        result = chat_completion.choices[0].message.content
        return result

    except Exception as e:
        print(f"❌ Error pada AI Engine: {e}")
        return None

# --- TESTING AREA (Jalan kalau file ini di-run langsung) ---
if __name__ == "__main__":
    # Data Palsu untuk Test
    dummy_data = [
        {
            "title": "Nvidia RTX 5090 Rilis Hari Ini",
            "link": "https://nvidia.com",
            "snippet": "GPU terbaru Nvidia diklaim 2x lebih cepat dari seri 4090 dengan harga yang kompetitif."
        },
        {
            "title": "Python 4.0 Sedang Dikembangkan",
            "link": "https://python.org",
            "snippet": "Rumor mengatakan Python 4.0 akan menghapus GIL sepenuhnya untuk performa multi-thread."
        }
    ]

    print("--- TEST GENERATE SUMMARY ---")
    hasil = generate_summary(dummy_data)
    
    if hasil:
        print("\n✅ Hasil Output (Raw HTML):")
        print(hasil)
    else:
        print("❌ Gagal generate.")